// This file contains all service-specific data including:
// - serviceElevet* arrays (benefits for each service)
// - serviceCompositeBonding* arrays (service descriptions)
// - serviceHero2Desc* arrays (hero descriptions)

// Due to the large size, this file re-exports from the original constants.ts
// In a future refactor, these can be split further

export {
  elevetTitleName,
  serviceElevetBridges,
  serviceElevet_Dentures,
  serviceElevet_Extractions,
  serviceElevet_WhiteFillings,
  serviceElevet_ScaleAndPolish,
  serviceElevet_Sedation,
  serviceElevet_Implants,
  serviceElevet_CrownsVeneers,
  serviceElevet_Examination,
  serviceElevet_Hygienist,
  serviceElevet_RootCanalTreatments,
  serviceElevet_Invisalign,
  serviceElevet_TeethWhitening,
  serviceElevet_CrownsVeneers2,
  serviceElevet_CompositeBonding,
  serviceElevet_InternalToothWhitening,
  serviceElevet_FixedRetainers,
  serviceElevet_ViveraRetainers,
  serviceElevet_CompositeVeneers,
  serviceElevet_RoutineExamination,
  serviceElevet_CompositeEdgeBonding,
  serviceCompositeBonding_Bridges,
  serviceCompositeBonding_Dentures,
  serviceCompositeBonding_Extractions,
  serviceCompositeBonding_WhiteFillings,
  serviceCompositeBonding_Sedation,
  serviceCompositeBonding_ScaleAndPolish,
  serviceCompositeBonding_CrownsVeneers,
  serviceCompositeBonding_Examination,
  serviceCompositeBonding_Hygienist,
  serviceCompositeBonding_RootCanalTreatments,
  serviceCompositeBonding_Invisalign,
  serviceCompositeBonding_TeethWhitening,
  serviceCompositeBonding_CrownsVeneers2,
  serviceCompositeBonding_Compositebonding,
  serviceCompositeBonding_Implants,
  serviceCompositeBonding_InternalToothWhitening,
  serviceCompositeBonding_FixedRetainers,
  serviceCompositeBonding_ViveraRetainers,
  serviceCompositeBonding_CompositeVeneers,
  serviceCompositeBonding_RoutineExamination,
  serviceCompositeBonding_CompositeEdgeBonding,
  serviceHero2DescBridge,
  serviceHero2DescDentures,
  serviceHero2DescExtyractions,
  serviceHero2Desc_WhiteFillings,
  serviceHero2Desc_ScaleAndPolish,
  serviceHero2Desc_Sedation,
  serviceHero2Desc_CrownsVeneers,
  serviceHero2Desc_Examination,
  serviceHero2Desc_Hygienist,
  serviceHero2Desc_RootCanalTreatments,
  serviceHero2Desc_Invisalign,
  serviceHero2Desc_teethwhitening,
  serviceHero2Desc_crowsVeneers2,
  serviceHero2Desc_compositeBonding,
  serviceHero2Desc_InternalToothWhitening,
  serviceHero2Desc_FixedRetainers,
  serviceHero2Desc_ViveraRetainers,
  serviceHero2Desc_CompositeVeneers,
  serviceHero2Desc_RoutineExamination,
  serviceHero2Desc_Implants,
  serviceHero2Desc_CompositeEdgebonding,
} from "../constants";
