export { default as Layout } from './Layout'
export { default as HomeHero } from './HomeHero'
export { default as Navbar } from './Navbar'
export { default as HomeAwards } from './HomeAwards'
export { default as HomeHero2 } from './HomeHero2'
export { default as HomePopularServices } from './HomePopularServices'
export { default as HomeOurServices } from './HomeOurServices'